name: mc-server

services:
  app:
    image: itzg/minecraft-server:latest
    restart: always
    stop_grace_period: 5m
    volumes:
      - $SERVER_DIR:/data
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      UID: $PUID
      GID: $PGID
      TZ: $TZ
    env_file: mc-server.env
