version: '3'

services:
  mc-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "create-extra"
      VERSION: "LATEST"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stop_grace_period: 5m
