version: '3'

services:
  mc-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      MOTD: "Les petits potes de PolyBot"
      DIFFICULTY: "normal"
      WHITELIST: |
        C0smic_Waves
      EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      OPS: |
        C0smic_Waves
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      ICON: "https://pasteboard.co/600EkKWvDvPC.png"
      OVERRIDE_ICON: "TRUE"
      MAX_PLAYERS: "5"
      VIEW_DISTANCE: "16"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "create-extra"
      VERSION: "LATEST"
      EULA: "TRUE"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stop_grace_period: 5m
