version: '3'

services:
  mc-server:
    image: itzg/minecraft-server:latest
    restart: always
    stop_grace_period: 5m
    tty: true
    stdin_open: true
    volumes:
      - $SERVER_DIR:/data
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    env_file: mc-server.env
